### ISSUE TITLE
Long double presicion

### ISSUE THREAD

**Issue by nquesada** [achan001/fsum#3]
Hey --- If I want to use fsum in long double (quad) presicion can I just take your code and change all the variables from double to long double?

Thanks!

**Comment by achan001** [comment]
Short answer: No
Long answer:

1. I use a static stack of 64 doubles, which covers 64x53 = 3392 bits
This is more than enough to hold sum of all doubles, max. bits of 53+1022+1023=2098
(Assuming all non-overlapping partials "touching" each other)
Long double precisions have much bigger exponent range, so a dynamic stack is advised.

2. Not just changing double to long double, but fabs(), isnan() ...

3. system had to setup with extended precision rounding, like fesetenv(FE_PC64_ENV)

4. The code might need to go through thousands of partials to update 1 addition :-(
